Adds simulation tests of invalidly-signed transactions.
obscuronet/obscuro-playground pull request #47
Opened 2022-03-23 10:11 UTC by joeldudley

2022-03-23 10:30 UTC, otherview approved these changes

2022-03-23 10:31 UTC, tudor-malene requested changes
Thanks Joel. This looks good but incomplete.
I don't see a check that these transactions are not included in the blockchain.

2022-03-23 10:32 UTC, joeldudley commented
@tudor-malene We already have tests of what's included in the blockchain as part of the simulation.

If these transactions were being included (rather than rejected), it would break those various checks (e.g. balances would be wrong, transfer numbers would be wrong...).

2022-03-23 11:04 UTC, tudor-malene commented
> @tudor-malene We already have tests of what's included in the blockchain as part of the simulation.
> 
> If these transactions were being included (rather than rejected), it would break those various checks (e.g. balances would be wrong, transfer numbers would be wrong...).

The checks are that the transactions that should be included were included. Not that there's no extra stuff.
Also, the balances are only checked holistically. That everything that was deposited minus everything that was successfully withdrawn is in the system.
There are no exact balance checks.

2022-03-24 15:25 UTC, tudor-malene commented on integration/simulation/transaction_manager.go
> +			to = rndWallet(m.wallets).Address
what if it's still the same value?

2022-03-24 15:25 UTC, tudor-malene commented on integration/simulation/transaction_manager.go
> +			to = rndWallet(m.wallets).Address
what if it's still the same value?

2022-03-24 15:57 UTC, joeldudley commented on integration/simulation/transaction_manager.go
> +			to = rndWallet(m.wallets).Address
It'll loop until it's different.

2022-03-24 15:57 UTC, joeldudley commented on integration/simulation/transaction_manager.go
> +			to = rndWallet(m.wallets).Address
It'll loop until it's different.

2022-03-24 15:58 UTC, joeldudley commented
@tudor-malene It is checking, because these are now invalid withdrawals. If they were accepted with the bad sigs, it would break the balance checks in the sim (you can try modifying the code so valid sigs are produced, and you'll see it breaks the test).

2022-03-25 14:16 UTC, tudor-malene commented on integration/simulation/transaction_manager.go
> +			to = rndWallet(m.wallets).Address
ah yes, I missed that.

2022-03-25 14:17 UTC, tudor-malene approved these changes
LGTM.
Got it now. Since you used withdrawals, it should be included in the checks.

2022-03-25 14:46 UTC, merged