Remove panic from block storage and refactor blockchain checking
obscuronet/obscuro-playground pull request #64
Opened 2022-03-28 17:09 UTC by tudor-malene

2022-03-30 13:49 UTC, joeldudley commented on integration/simulation/stats.go
> +	// totalL2Txs  int
Delete?

2022-03-30 13:54 UTC, joeldudley commented
@tudor-malene Do you need to update the go.mod or something? It was complaining about this line in `validate_chain.go` 
until I did a `go get ./...`:

`collect "github.com/sxyazi/go-collection"`

2022-03-30 13:55 UTC, joeldudley commented on integration/simulation/validate_chain.go
> +// After a simulation has run, check as much as possible that everything has
"that everything has" what?

2022-03-30 13:56 UTC, joeldudley commented on integration/simulation/validate_chain.go
> +// - check height is similar
maybe `- check height is similar across nodes`?

2022-03-30 14:01 UTC, joeldudley commented on integration/simulation/validate_chain.go
> +	// walk the blocks in reverse direction, execute deposits and transactions and compare to the state in the rollup
Should this also be a todo?

2022-03-30 14:03 UTC, joeldudley requested changes
LGTM. A few small things.

2022-04-01 14:45 UTC, tudor-malene commented
back to you @joeldudley

2022-04-04 08:11 UTC, joeldudley approved these changes
LGTM

2022-04-04 08:53 UTC, merged